version: '3'
services:
  app: &app
    build:
      context: .
      args:
        RUBY_VERSION: '2.6.5'
        NODE_MAJOR: '10'
        YARN_VERSION: '1.19.1'
        BUNDLER_VERSION: '2.0.2'
    tmpfs:
      - /tmp
  web:
    <<: *app
    container_name: xiusin_web
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres@db
      WEBPACKER_DEV_SERVER_HOST: webpacker
    depends_on:
      - db
      - webpacker
  webpacker:
    <<: *app
    container_name: xiusin_webpacker
    command: ./bin/webpack-dev-server
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - 3035:3035
  db:
    container_name: xiusin_postgres
    image: postgres:12.0
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data